version: "2"
services: 
  casino:
    build: ./casino/server/ 
    ports: 
      - "1337:1337"
    container_name: casino
    mem_limit: 200m 
    restart: always 
  easy_casino:
    build: ./easy_casino/server/ 
    ports: 
      - "7337:1337"
    container_name: easy_casino
    mem_limit: 200m 
    restart: always 


